CAUTION_TEMP: 82
DANGER_TEMP: 90
DISKOPS_CAUTION: 120
DISK_ID: disable
FONT_SIZE: 8
MAX_CPU_MHZ: 5500
NETOPS_CAUTION: 350
NUM_SAMPLES: 30
POLL_INTERVAL_MS: 1000
ROW_HEIGHT: 20
UTILIZATION_CAUTION: 95
UTIL_SAMPLES: 10
WIDTH: 280
X_LOCATION: 3
Y_LOCATION: 1551
